[tool.black]
line-length = 120
target-version = ['py39']

[tool.ruff]
line-length = 120
ignore = ['D203']

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-ra --cov --cov-fail-under=100"
